#!/usr/bin/env bash

mkdir -p "$HOME/personal"

GIT_SSL_NO_VERIFY=1 git clone https://aur.archlinux.org/paru.git "$HOME/personal/paru" || echo "Already cloned. Skipping."
cd "$HOME/personal/paru"
makepkg -si --noconfirm

paru -S ghostty --needed --noconfirm
