#!/usr/bin/env bash

mkdir -p "$HOME/personal"

if [[ ! -d "$HOME/personal/paru" ]]; then
GIT_SSL_NO_VERIFY=1 git clone https://aur.archlinux.org/paru.git "$HOME/personal/paru"
  cd "$HOME/personal/paru"
  makepkg -si --noconfirm
else
  echo "paru already installed, skipping"
fi

#paru -S --noconfirm --needed hyprland
sudo pacman -S hyprland --needed --noconfirm

paru -S --needed --noconfirm sddm-git
paru -S --needed --noconfirm mako # notification daemon

sudo pacman -S --needed --noconfirm pipewire wireplumber # screen sharing
sudo pacman -S --needed --noconfirm xdg-desktop-portal xdg-desktop-portal-hyprland
paru -S --needed --noconfirm hyprland-polkit-agent # handles gui popups
sudo pacman -S --needed --noconfirm qt5-wayland qt6-wayland # qt app support

sudo pacman -S --needed --noconfirm hyprpaper
paru -S hyprpicker-git --needed --noconfirm # color picker
sudo pacman -S udiskie --needed --noconfirm # auto mount usbs etc




#sudo pacman -S hyprland-plugins   # gives you hyprpaper, hyprshot, scratchpad, hyprctrl

