#!bin/bash/env bash

mkdir -p "$HOME/personal"

if [[ ! -d "$HOME/personal/paru" ]]; then
  git clone https://aur.archlinux.org/paru.git "$HOME/personal/paru"
  cd "$HOME/personal/paru"
  makepkg -si --noconfirm
else
  echo "paru already installed, skipping"
fi
