#!/usr/bin/env bash
#paru -S rofi-lbonn-wayland

if [[ ! -d "$HOME/personal/paru" ]]; then
  git clone https://aur.archlinux.org/paru.git "$HOME/personal/paru"
  cd "$HOME/personal/paru"
  makepkg -si --noconfirm
else
  echo "paru already installed, skipping"
fi

paru -S --needed --noconfirm rofi-wayland
