#!/usr/bin/env bash
#paru -S rofi-lbonn-wayland

sudo pacman -S --needed --noconfirm base-devel

git clone https://aur.archlinux.org/paru.git $HOME/personal/paru
cd $HOME/personal/paru
makepkg -si --noconfirm

paru -S --needed --noconfirm rofi-wayland
